# coding: utf-8

"""
    Human Resources API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems


class EmployeeRewardApiModel(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, employee_id=None, name=None, phones=None, orders=None):
        """
        EmployeeRewardApiModel - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'employee_id': 'int',
            'name': 'str',
            'phones': 'int',
            'orders': 'int'
        }

        self.attribute_map = {
            'employee_id': 'employee_id',
            'name': 'name',
            'phones': 'phones',
            'orders': 'orders'
        }

        self._employee_id = employee_id
        self._name = name
        self._phones = phones
        self._orders = orders

    @property
    def employee_id(self):
        """
        Gets the employee_id of this EmployeeReward.

        :return: The employee_id of this EmployeeReward.
        :rtype: int
        """
        return self._employee_id

    @employee_id.setter
    def employee_id(self, employee_id):
        """
        Sets the employee_id of this EmployeeReward.

        :param employee_id: The employee_id of this EmployeeReward.
        :type: int
        """

        self._employee_id = employee_id

    @property
    def name(self):
        """
        Gets the name of this EmployeeReward.

        :return: The name of this EmployeeReward.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this EmployeeReward.

        :param name: The name of this EmployeeReward.
        :type: str
        """

        self._name = name

    @property
    def phones(self):
        """
        Gets the phones of this EmployeeReward.

        :return: The phones of this EmployeeReward.
        :rtype: int
        """
        return self._phones

    @phones.setter
    def phones(self, phones):
        """
        Sets the phones of this EmployeeReward.

        :param phones: The phones of this EmployeeReward.
        :type: int
        """

        self._phones = phones

    @property
    def orders(self):
        """
        Gets the orders of this EmployeeReward.

        :return: The orders of this EmployeeReward.
        :rtype: int
        """
        return self._orders

    @orders.setter
    def orders(self, orders):
        """
        Sets the orders of this EmployeeReward.

        :param orders: The orders of this EmployeeReward.
        :type: int
        """

        self._orders = orders

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EmployeeRewardApiModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
